### ISSUE TITLE
pywws2weewx: ValueError("invalid literal for int() with base 10: ''")

### ISSUE THREAD

**Issue by mfraser** [LapplandsCohan/pywws2weewx#1]
Tried to run pywws2weewx on some data, but got the error message:
pywws2weewx: ValueError("invalid literal for int() with base 10: ''")

Data that worked is in the format:
2017-01-01 23:57:18,5,36,23.0,84,3.6,1020.9,2.4,3.7,14,660.3,0,35.6,0
And the data that gave the error:
2021-03-01 00:04:00,5,49,22.4,77,5.3,1022.7,0.3,0.7,12,0.3,0,0,0

**Comment by LapplandsCohan** [comment]
By just a quick look I can't see what is causing this issue. I will have to dig deeper, but time is a bit limited the coming weeks.

**Comment by mfraser** [comment]
> By just a quick look I can't see what is causing this issue. I will have to dig deeper, but time is a bit limited the coming weeks.

I'll try running with DEBUG = 1 and see if that shows what the issue is.

**Comment by mfraser** [comment]
Data point 2019-12-15 19:12:00 has a status flag! 64
Traceback (most recent call last):
  File "/home/mfraser/bin/pywws2weewx", line 399, in <module>
    sys.exit(main())
  File "/home/mfraser/bin/pywws2weewx", line 277, in main
    raise(e)
  File "/home/mfraser/bin/pywws2weewx", line 244, in main
    process_directory(inpath)
  File "/home/mfraser/bin/pywws2weewx", line 289, in process_directory
    process_directory(entry.path)
  File "/home/mfraser/bin/pywws2weewx", line 289, in process_directory
    process_directory(entry.path)
  File "/home/mfraser/bin/pywws2weewx", line 291, in process_directory
    process_file(entry.path)
  File "/home/mfraser/bin/pywws2weewx", line 315, in process_file
    dataset.append(pywwsDatapoint(*datapoint))
  File "/home/mfraser/bin/pywws2weewx", line 87, in __init__
    self.wind_dir_deg         = int(wind_dir)*22.5                      # Convert indexed direction to degrees
ValueError: invalid literal for int() with base 10: ''

**Comment by LapplandsCohan** [comment]
Both lines in your initial post parse without error for me. Which arguments do you use when running the script?

The last comment seem to be on a different data post than the two in the original post. Could you please share that line, or preferably the whole file for that day?

Your dataset seem to include illuminance and uv data. My data was from an older version of pywws which didn't save these values in the database. (And my weather station back then didn't collect them either…) Could you share a dataset (at least two consecutive days) so I can test input with these fields as well?

**Comment by LapplandsCohan** [comment]
This could be a line ending issue, but then it should always occur, and not just some some datapoints.
Can you try changing line 314 from
`datapoint = line.replace('\n', '').split(",")`
to
`datapoint = line.replace('\n', '').replace('\r', '').split(",")`

**Comment by mfraser** [comment]
> 

Verbose mode 4
Specified paths: ['2019-12/2019-12-15.txt']
Recursive mode True
Infile include regex: ^\d{4}-\d{2}-\d{2}\.txt$
Starting processing file: 2019-12-15.txt
Data point 2019-12-15 19:12:00 has a status flag! 64
Traceback (most recent call last):
  File "/home/mfraser/bin/pywws2weewx.py", line 399, in <module>
    sys.exit(main())
  File "/home/mfraser/bin/pywws2weewx.py", line 277, in main
    raise(e)
  File "/home/mfraser/bin/pywws2weewx.py", line 242, in main
    process_file(inpath)
  File "/home/mfraser/bin/pywws2weewx.py", line 315, in process_file
    dataset.append(pywwsDatapoint(*datapoint))
  File "/home/mfraser/bin/pywws2weewx.py", line 87, in __init__
    self.wind_dir_deg         = int(wind_dir)*22.5                      # Convert indexed direction to degrees
ValueError: invalid literal for int() with base 10: ''

**Comment by mfraser** [comment]
[2019-12.tar.gz](https://github.com/LapplandsCohan/pywws2weewx/files/9034216/2019-12.tar.gz)
2019-12-15.txt is one of the files generating the error.
